// data.js

export const data = {
    strings: [
      {
        name: "Sitar",
        category: "strings",
        origin: "India",
        importance: "Used in classical Indian music.",
        masters: ["Ravi Shankar", "Anoushka Shankar"],
        genres: ["Classical", "Fusion", "Folk"],
        priceRange: "₹10,000 – ₹80,000",
        famousWorks: ["Ravi Shankar – Raga Jog"],
        image: "https://cdn.pixabay.com/photo/2020/03/21/07/51/tambura-4952939_1280.jpg",
        audioSample: "https://example.com/sitar-sound.mp3"
      },
      {
        name: "Guitar",
        category: "strings",
        origin: "Spain",
        importance: "Popular in nearly all music styles.",
        masters: ["Jimi Hendrix", "Eric Clapton"],
        genres: ["Rock", "Pop", "Blues", "Folk"],
        priceRange: "₹5,000 – ₹2,00,000",
        famousWorks: ["Jimi Hendrix – Little Wing"],
        image: "https://cdn.pixabay.com/photo/2024/02/26/19/51/guitar-8598823_640.jpg",
        audioSample: "https://example.com/guitar.mp3"
      },
      {
        name: "Violin",
        category: "strings",
        origin: "Italy",
        importance: "Core instrument in orchestras and classical music.",
        masters: ["Niccolò Paganini", "Itzhak Perlman"],
        genres: ["Classical", "Folk", "Film music"],
        priceRange: "₹7,000 – ₹5,00,000",
        famousWorks: ["Paganini – Caprice No. 24"],
        image: "https://cdn.pixabay.com/photo/2013/07/13/10/06/violin-156558_640.png",
        audioSample: "https://example.com/violin.mp3"
      },
      {
        name: "Sarod",
        category: "strings",
        origin: "India",
        importance: "Key instrument in Hindustani classical music.",
        masters: ["Amjad Ali Khan"],
        genres: ["Classical"],
        priceRange: "₹20,000 – ₹1,50,000",
        famousWorks: ["Amjad Ali Khan – Raga Marwa"],
        image: "https://example.com/sarod.jpg",
        audioSample: "https://example.com/sarod.mp3"
      },
      {
        name: "Harp",
        category: "strings",
        origin: "Ancient Egypt",
        importance: "Used in classical and orchestral compositions.",
        masters: ["Nancy Allen", "Ann Hobson"],
        genres: ["Classical"],
        priceRange: "₹50,000 – ₹10,00,000",
        famousWorks: ["Debussy – Danse sacrée et danse profane"],
        image: "https://cdn.pixabay.com/photo/2013/10/14/19/15/harp-195636_640.jpg",
        audioSample: "https://example.com/harp.mp3"
      },
      {
        name: "Ukulele",
        category: "strings",
        origin: "Hawaii",
        importance: "Popular for light, cheerful music and performances.",
        masters: ["Israel Kamakawiwo’ole"],
        genres: ["Folk", "Pop"],
        priceRange: "₹2,000 – ₹20,000",
        famousWorks: ["Somewhere Over the Rainbow – Israel Kamakawiwo’ole"],
        image: "https://cdn.pixabay.com/photo/2016/05/06/19/25/ukulele-1376516_640.jpg",
        audioSample: "https://example.com/ukulele.mp3"
      },
      {
        name: "Cello",
        category: "strings",
        origin: "Italy",
        importance: "Deep expressive tone used in orchestras.",
        masters: ["Yo-Yo Ma"],
        genres: ["Classical", "Film music"],
        priceRange: "₹20,000 – ₹6,00,000",
        famousWorks: ["Bach Cello Suites"],
        image: "https://cdn.pixabay.com/photo/2024/03/11/18/29/cello-8627393_640.jpg",
        audioSample: "https://example.com/cello.mp3"
      },
      {
        name: "Mandolin",
        category: "strings",
        origin: "Italy",
        importance: "Used in folk, Indian classical & bluegrass.",
        masters: ["U. Srinivas"],
        genres: ["Classical", "Folk"],
        priceRange: "₹5,000 – ₹60,000",
        famousWorks: ["U. Srinivas – Mandolin Raga"],
        image: "https://cdn.pixabay.com/photo/2018/12/19/00/06/mandolin-3883302_640.jpg",
        audioSample: "https://example.com/mandolin.mp3"
      },
      {
        name: "Banjo",
        category: "strings",
        origin: "African-American culture",
        importance: "Key instrument in country and bluegrass music.",
        masters: ["Earl Scruggs"],
        genres: ["Country", "American Folk"],
        priceRange: "₹7,000 – ₹70,000",
        famousWorks: ["Foggy Mountain Breakdown"],
        image: "https://cdn.pixabay.com/photo/2018/05/03/20/10/banjo-3372248_640.png",
        audioSample: "https://example.com/banjo.mp3"
      },
      {
        name: "Veena",
        category: "strings",
        origin: "India",
        importance: "Major instrument in Carnatic classical music.",
        masters: ["Jayanthi Kumaresh"],
        genres: ["Classical"],
        priceRange: "₹15,000 – ₹1,00,000",
        famousWorks: ["Veena concert by Jayanthi Kumaresh"],
        image: "https://example.com/veena.jpg",
        audioSample: "https://example.com/veena.mp3"
      }
    ],
  
    percussion: [
      {
        name: "Tabla",
        category: "percussion",
        origin: "India",
        importance: "Primary percussion in Hindustani classical.",
        masters: ["Zakir Hussain"],
        genres: ["Classical", "Folk"],
        priceRange: "₹4,000 – ₹40,000",
        famousWorks: ["Zakir Hussain – Tabla Solo"],
        image: "https://cdn.pixabay.com/photo/2015/05/03/18/03/drum-751456_640.jpg",
        audioSample: "https://example.com/tabla.mp3"
      },
      {
        name: "Drums",
        category: "percussion",
        origin: "Africa",
        importance: "Core of modern bands.",
        masters: ["Neil Peart"],
        genres: ["Rock", "Jazz"],
        priceRange: "₹10,000 – ₹3,00,000",
        famousWorks: ["Tom Sawyer – Rush"],
        image: "https://cdn.pixabay.com/photo/2020/07/03/05/52/music-5365267_640.png",
        audioSample: "https://example.com/drums.mp3"
      },
      {
        name: "Dhol",
        category: "percussion",
        origin: "India",
        importance: "Popular in Punjabi & folk music.",
        masters: ["Nav Bajwa"],
        genres: ["Folk", "Bhangra"],
        priceRange: "₹2,000 – ₹20,000",
        famousWorks: ["Bhangra beats"],
        image: "https://cdn.pixabay.com/photo/2022/01/05/05/53/music-6916427_1280.jpg",
        audioSample: "https://example.com/dhol.mp3"
      },
      {
        name: "Mridangam",
        category: "percussion",
        origin: "India",
        importance: "Primary percussion in Carnatic music.",
        masters: ["Umayalpuram Sivaraman"],
        genres: ["Classical"],
        priceRange: "₹5,000 – ₹60,000",
        famousWorks: ["Carnatic percussion solo"],
        image: "https://example.com/mridangam.jpg",
        audioSample: "https://example.com/mridangam.mp3"
      },
      {
        name: "Cajón",
        category: "percussion",
        origin: "Peru",
        importance: "Portable percussion used in acoustic music.",
        masters: ["Alex Acuña"],
        genres: ["Acoustic", "Latin"],
        priceRange: "₹3,000 – ₹20,000",
        famousWorks: ["Latin percussion tracks"],
        image: "https://example.com/cajon.jpg",
        audioSample: "https://example.com/cajon.mp3"
      },
      {
        name: "Conga",
        category: "percussion",
        origin: "Cuba",
        importance: "Used in Latin, salsa, and Afro-Cuban music.",
        masters: ["Tito Puente"],
        genres: ["Latin"],
        priceRange: "₹6,000 – ₹50,000",
        famousWorks: ["Salsa classics"],
        image: "https://cdn.pixabay.com/photo/2016/09/11/10/59/cajon-1661111_640.png",
        audioSample: "https://example.com/conga.mp3"
      },
      {
        name: "Bongo",
        category: "percussion",
        origin: "Cuba",
        importance: "Bright rhythms in Latin music.",
        masters: ["Jack Costanzo"],
        genres: ["Latin", "Jazz"],
        priceRange: "₹2,000 – ₹15,000",
        famousWorks: ["Latin jazz"],
        image: "https://cdn.pixabay.com/photo/2013/03/23/19/04/drum-96179_640.jpg",
        audioSample: "https://example.com/bongo.mp3"
      },
      {
        name: "Djembe",
        category: "percussion",
        origin: "West Africa",
        importance: "Traditional African drum.",
        masters: ["Mamady Keïta"],
        genres: ["African folk"],
        priceRange: "₹4,000 – ₹30,000",
        famousWorks: ["African drum performances"],
        image: "https://cdn.pixabay.com/photo/2015/11/24/18/00/african-1060423_640.jpg",
        audioSample: "https://example.com/djembe.mp3"
      },
      {
        name: "Pakhawaj",
        category: "percussion",
        origin: "India",
        importance: "Ancient drum used in Dhrupad music.",
        masters: ["Ramakant Dugge"],
        genres: ["Classical"],
        priceRange: "₹5,000 – ₹50,000",
        famousWorks: ["Dhrupad performances"],
        image: "https://example.com/pakhawaj.jpg",
        audioSample: "https://example.com/pakhawaj.mp3"
      },
      {
        name: "Tambourine",
        category: "percussion",
        origin: "Middle East",
        importance: "Used in folk & modern music.",
        masters: [],
        genres: ["Pop", "Folk"],
        priceRange: "₹300 – ₹2,000",
        famousWorks: ["Pop songs"],
        image: "https://cdn.pixabay.com/photo/2013/11/28/09/51/tambourine-219732_640.jpg",
        audioSample: "https://example.com/tambourine.mp3"
      }
    ],
  
    wind: [
      {
        name: "Flute",
        category: "wind",
        origin: "Ancient India",
        importance: "Light, melodic instrument used in many genres.",
        masters: ["Hariprasad Chaurasia"],
        genres: ["Classical", "Folk", "Film"],
        priceRange: "₹500 – ₹10,000",
        famousWorks: ["Raga Brindavani Sarang – Chaurasia"],
        image: "https://cdn.pixabay.com/photo/2017/09/07/01/45/illustration-2723678_640.png",
        audioSample: "https://example.com/flute.mp3"
      },
      {
        name: "Shehnai",
        category: "wind",
        origin: "India",
        importance: "Popular in weddings & classical music.",
        masters: ["Bismillah Khan"],
        genres: ["Classical", "Folk"],
        priceRange: "₹3,000 – ₹40,000",
        famousWorks: ["Bismillah Khan – Shehnai"],
        image: "https://example.com/shehnai.jpg",
        audioSample: "https://example.com/shehnai.mp3"
      },
      {
        name: "Saxophone",
        category: "wind",
        origin: "Belgium",
        importance: "Key instrument in jazz music.",
        masters: ["John Coltrane"],
        genres: ["Jazz", "Blues"],
        priceRange: "₹15,000 – ₹2,00,000",
        famousWorks: ["Giant Steps – Coltrane"],
        image: "https://cdn.pixabay.com/photo/2016/09/15/21/09/saxophone-1672675_640.png",
        audioSample: "https://example.com/saxophone.mp3"
      },
      {
        name: "Clarinet",
        category: "wind",
        origin: "Germany",
        importance: "Used in orchestras and jazz.",
        masters: ["Benny Goodman"],
        genres: ["Jazz", "Classical"],
        priceRange: "₹7,000 – ₹60,000",
        famousWorks: ["Sing Sing Sing"],
        image: "https://cdn.pixabay.com/photo/2016/10/16/04/51/music-1744419_640.jpg",
        audioSample: "https://example.com/clarinet.mp3"
      },
      {
        name: "Trumpet",
        category: "wind",
        origin: "Egypt",
        importance: "Bright tone for jazz & bands.",
        masters: ["Louis Armstrong"],
        genres: ["Jazz", "Blues"],
        priceRange: "₹5,000 – ₹70,000",
        famousWorks: ["What a Wonderful World"],
        image: "https://cdn.pixabay.com/photo/2020/03/31/13/33/music-4987649_640.jpg",
        audioSample: "https://example.com/trumpet.mp3"
      },
      {
        name: "Harmonica",
        category: "wind",
        origin: "Germany",
        importance: "Popular in blues & folk.",
        masters: ["Larry Adler"],
        genres: ["Blues", "Folk"],
        priceRange: "₹200 – ₹3,000",
        famousWorks: ["Blues classics"],
        image: "https://cdn.pixabay.com/photo/2015/02/18/20/23/harmonica-641425_640.jpg",
        audioSample: "https://example.com/harmonica.mp3"
      },
      {
        name: "Bagpipe",
        category: "wind",
        origin: "Scotland",
        importance: "Used in folk & military bands.",
        masters: [],
        genres: ["Folk"],
        priceRange: "₹5,000 – ₹80,000",
        famousWorks: ["Scottish folk tunes"],
        image: "https://cdn.pixabay.com/photo/2018/05/03/20/10/bagpipes-3372246_640.png",
        audioSample: "https://example.com/bagpipe.mp3"
      },
      {
        name: "Oboe",
        category: "wind",
        origin: "France",
        importance: "Used in orchestras for rich tone.",
        masters: [],
        genres: ["Classical"],
        priceRange: "₹20,000 – ₹1,50,000",
        famousWorks: ["Oboe concertos"],
        image: "https://cdn.pixabay.com/photo/2012/04/15/18/24/oboe-34796_640.png",
        audioSample: "https://example.com/oboe.mp3"
      },
      {
        name: "Didgeridoo",
        category: "wind",
        origin: "Australia",
        importance: "Traditional Aboriginal instrument.",
        masters: [],
        genres: ["Tribal"],
        priceRange: "₹3,000 – ₹20,000",
        famousWorks: ["Australian tribal music"],
        image: "https://cdn.pixabay.com/photo/2013/07/12/16/58/didgeridoo-151580_1280.png",
        audioSample: "https://example.com/didgeridoo.mp3"
      },
      {
        name: "Pan Flute",
        category: "wind",
        origin: "Romania",
        importance: "Soft melodic sound used in folk music.",
        masters: ["Gheorghe Zamfir"],
        genres: ["Folk"],
        priceRange: "₹1,000 – ₹15,000",
        famousWorks: ["The Lonely Shepherd"],
        image: "https://cdn.pixabay.com/photo/2015/02/28/12/19/pan-flute-653495_640.jpg",
        audioSample: "https://example.com/panflute.mp3"
      }
    ],
  
    electronic: [
      {
        name: "Synthesizer",
        category: "electronic",
        origin: "USA",
        importance: "Key instrument in electronic, pop, and film scores.",
        masters: ["Hans Zimmer"],
        genres: ["Electronic", "Pop", "Film"],
        priceRange: "₹5,000 – ₹2,00,000",
        famousWorks: ["Interstellar Theme"],
        image: "https://cdn.pixabay.com/photo/2016/08/18/00/48/vintage-synthesizer-1601941_640.jpg",
        audioSample: "https://example.com/synth.mp3"
      },
      {
        name: "Electric Guitar",
        category: "electronic",
        origin: "USA",
        importance: "Foundation of rock & metal music.",
        masters: ["Slash"],
        genres: ["Rock"],
        priceRange: "₹10,000 – ₹3,00,000",
        famousWorks: ["Sweet Child O’ Mine"],
        image: "https://cdn.pixabay.com/photo/2018/11/27/17/32/electric-guitar-3841897_640.jpg",
        audioSample: "https://example.com/electricguitar.mp3"
      },
      {
        name: "Drum Machine",
        category: "electronic",
        origin: "Japan",
        importance: "Used to create beats in EDM & hip-hop.",
        masters: [],
        genres: ["EDM", "Hip-Hop"],
        priceRange: "₹5,000 – ₹50,000",
        famousWorks: ["Electronic tracks"],
        image: "https://cdn.pixabay.com/photo/2022/08/30/04/13/studio-7420221_640.jpg",
        audioSample: "https://example.com/drummachine.mp3"
      },
      {
        name: "Keyboard",
        category: "electronic",
        origin: "USA",
        importance: "Popular for beginners & professional music.",
        masters: [],
        genres: ["Pop", "Rock"],
        priceRange: "₹3,000 – ₹1,00,000",
        famousWorks: ["Live band music"],
        image: "https://cdn.pixabay.com/photo/2021/11/16/13/43/instrument-6800993_640.jpg",
        audioSample: "https://example.com/keyboard.mp3"
      },
      {
        name: "Sampler",
        category: "electronic",
        origin: "USA",
        importance: "Used to create remixes & loops.",
        masters: [],
        genres: ["EDM", "Hip-Hop"],
        priceRange: "₹5,000 – ₹80,000",
        famousWorks: ["Electronic remixes"],
        image: "https://cdn.pixabay.com/photo/2021/11/26/10/14/groovebox-6825553_1280.png",
        audioSample: "https://example.com/sampler.mp3"
      },
      {
        name: "Electric Violin",
        category: "electronic",
        origin: "USA",
        importance: "Modern version for concerts & fusion.",
        masters: [],
        genres: ["Fusion", "Pop"],
        priceRange: "₹7,000 – ₹70,000",
        famousWorks: [],
        image: "https://cdn.pixabay.com/photo/2014/06/06/10/19/music-363276_640.jpg",
        audioSample: "https://example.com/electricviolin.mp3"
      },
      {
        name: "Turntable",
        category: "electronic",
        origin: "USA",
        importance: "Used by DJs for scratching & mixing.",
        masters: [],
        genres: ["Hip-Hop", "EDM"],
        priceRange: "₹15,000 – ₹1,50,000",
        famousWorks: ["DJ mixes"],
        image: "https://cdn.pixabay.com/photo/2023/02/16/03/43/music-player-7792956_640.jpg",
        audioSample: "https://example.com/turntable.mp3"
      },
      {
        name: "Digital Drum Pad",
        category: "electronic",
        origin: "Japan",
        importance: "Used for live drumming & beat making.",
        masters: [],
        genres: ["EDM", "Pop"],
        priceRange: "₹5,000 – ₹30,000",
        famousWorks: [],
        image: "https://cdn.pixabay.com/photo/2020/12/23/09/56/electronic-drum-pad-5854409_1280.jpg",
        audioSample: "https://example.com/drumpad.mp3"
      },
      {
        name: "Theremin",
        category: "electronic",
        origin: "Russia",
        importance: "Touchless instrument used in sci-fi music.",
        masters: [],
        genres: ["Experimental"],
        priceRange: "₹10,000 – ₹40,000",
        famousWorks: ["Sci-fi film scores"],
        image: "https://example.com/theremin.jpg",
        audioSample: "https://example.com/theremin.mp3"
      },
      {
        name: "Electric Bass",
        category: "electronic",
        origin: "USA",
        importance: "Deep bass lines for modern music.",
        masters: ["Victor Wooten"],
        genres: ["Rock", "Funk"],
        priceRange: "₹10,000 – ₹1,50,000",
        famousWorks: [],
        image: "https://cdn.pixabay.com/photo/2015/05/27/20/55/electric-bass-787204_640.jpg",
        audioSample: "https://example.com/bass.mp3"
      }
    ]
  };
  
